openapi: 3.0.0
info:
  $ref: './info.yaml'
servers:
  $ref: './servers.yaml'
components:
  $ref: './components/schemas.yaml'
paths:
  $ref: './paths/register.yaml'
  $ref: './paths/login.yaml'
  $ref: './paths/logout.yaml'
