openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Money Guard app
tags:
  - name: Transactions
    description: Operations about transactions.
  - name: Auth
    description: Auth operations.
  - name: User
    description: User operations.
servers:
  - url: https://moneyg-01-back.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /user/current:
    get:
      $ref: '../swagger/paths/user/current.yaml'
  /user/update:
    patch:
      $ref: '../swagger/paths/user/update.yaml'
  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml
    post:
      $ref: ../swagger/paths/transactions/post.yaml
  /transactions/{id}:
    get:
      $ref: '../swagger/paths/transactions/{id}/get.yaml'
    delete:
      $ref: '../swagger/paths/transactions/{id}/delete.yaml'
    patch:
      $ref: '../swagger/paths/transactions/{id}/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
